/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  IsString,
  IsOptional,
  ValidateNested,
  IsDate,
  IsInt,
} from "class-validator";
import { DocumentTypeWhereUniqueInput } from "../../documentType/base/DocumentTypeWhereUniqueInput";
import { Type } from "class-transformer";
import { PoItemCreateNestedManyWithoutPoHeadersInput } from "./PoItemCreateNestedManyWithoutPoHeadersInput";
import { SupplierWhereUniqueInput } from "../../supplier/base/SupplierWhereUniqueInput";

@InputType()
class PoHeaderCreateInput {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  amount!: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  currency?: string | null;

  @ApiProperty({
    required: false,
    type: () => DocumentTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DocumentTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => DocumentTypeWhereUniqueInput, {
    nullable: true,
  })
  docType?: DocumentTypeWhereUniqueInput | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  documentDate!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  documentNo!: number;

  @ApiProperty({
    required: false,
    type: () => PoItemCreateNestedManyWithoutPoHeadersInput,
  })
  @ValidateNested()
  @Type(() => PoItemCreateNestedManyWithoutPoHeadersInput)
  @IsOptional()
  @Field(() => PoItemCreateNestedManyWithoutPoHeadersInput, {
    nullable: true,
  })
  poItems?: PoItemCreateNestedManyWithoutPoHeadersInput;

  @ApiProperty({
    required: true,
    type: () => SupplierWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SupplierWhereUniqueInput)
  @Field(() => SupplierWhereUniqueInput)
  supplierNo!: SupplierWhereUniqueInput;
}

export { PoHeaderCreateInput };
