/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UnitOfMeasureService } from "../unitOfMeasure.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UnitOfMeasureCreateInput } from "./UnitOfMeasureCreateInput";
import { UnitOfMeasureWhereInput } from "./UnitOfMeasureWhereInput";
import { UnitOfMeasureWhereUniqueInput } from "./UnitOfMeasureWhereUniqueInput";
import { UnitOfMeasureFindManyArgs } from "./UnitOfMeasureFindManyArgs";
import { UnitOfMeasureUpdateInput } from "./UnitOfMeasureUpdateInput";
import { UnitOfMeasure } from "./UnitOfMeasure";
import { MaterialFindManyArgs } from "../../material/base/MaterialFindManyArgs";
import { Material } from "../../material/base/Material";
import { MaterialWhereUniqueInput } from "../../material/base/MaterialWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UnitOfMeasureControllerBase {
  constructor(
    protected readonly service: UnitOfMeasureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UnitOfMeasure })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: UnitOfMeasureCreateInput
  ): Promise<UnitOfMeasure> {
    return await this.service.create({
      data: {
        ...data,

        poItem: data.poItem
          ? {
              connect: data.poItem,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        poItem: {
          select: {
            id: true,
          },
        },

        uomCode: true,
        uoMDescription: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [UnitOfMeasure] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UnitOfMeasureFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<UnitOfMeasure[]> {
    const args = plainToClass(UnitOfMeasureFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        poItem: {
          select: {
            id: true,
          },
        },

        uomCode: true,
        uoMDescription: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UnitOfMeasure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UnitOfMeasureWhereUniqueInput
  ): Promise<UnitOfMeasure | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        poItem: {
          select: {
            id: true,
          },
        },

        uomCode: true,
        uoMDescription: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UnitOfMeasure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UnitOfMeasureWhereUniqueInput,
    @common.Body() data: UnitOfMeasureUpdateInput
  ): Promise<UnitOfMeasure | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          poItem: data.poItem
            ? {
                connect: data.poItem,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          poItem: {
            select: {
              id: true,
            },
          },

          uomCode: true,
          uoMDescription: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UnitOfMeasure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UnitOfMeasureWhereUniqueInput
  ): Promise<UnitOfMeasure | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          poItem: {
            select: {
              id: true,
            },
          },

          uomCode: true,
          uoMDescription: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/materialsUoM")
  @ApiNestedQuery(MaterialFindManyArgs)
  async findManyMaterialsUoM(
    @common.Req() request: Request,
    @common.Param() params: UnitOfMeasureWhereUniqueInput
  ): Promise<Material[]> {
    const query = plainToClass(MaterialFindManyArgs, request.query);
    const results = await this.service.findMaterialsUoM(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        materialDescription: true,
        materialNo: true,

        uoMCode: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/materialsUoM")
  async connectMaterialsUoM(
    @common.Param() params: UnitOfMeasureWhereUniqueInput,
    @common.Body() body: MaterialWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      materialsUoM: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/materialsUoM")
  async updateMaterialsUoM(
    @common.Param() params: UnitOfMeasureWhereUniqueInput,
    @common.Body() body: MaterialWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      materialsUoM: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "UnitOfMeasure",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/materialsUoM")
  async disconnectMaterialsUoM(
    @common.Param() params: UnitOfMeasureWhereUniqueInput,
    @common.Body() body: MaterialWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      materialsUoM: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
