/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PoItemListRelationFilter } from "../../poItem/base/PoItemListRelationFilter";
import { UnitOfMeasureWhereUniqueInput } from "../../unitOfMeasure/base/UnitOfMeasureWhereUniqueInput";

@InputType()
class MaterialWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  materialDescription?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  materialNo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PoItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PoItemListRelationFilter)
  @IsOptional()
  @Field(() => PoItemListRelationFilter, {
    nullable: true,
  })
  poItems?: PoItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UnitOfMeasureWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UnitOfMeasureWhereUniqueInput)
  @IsOptional()
  @Field(() => UnitOfMeasureWhereUniqueInput, {
    nullable: true,
  })
  uoMCode?: UnitOfMeasureWhereUniqueInput;
}

export { MaterialWhereInput };
