/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MaterialService } from "../material.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MaterialCreateInput } from "./MaterialCreateInput";
import { MaterialWhereInput } from "./MaterialWhereInput";
import { MaterialWhereUniqueInput } from "./MaterialWhereUniqueInput";
import { MaterialFindManyArgs } from "./MaterialFindManyArgs";
import { MaterialUpdateInput } from "./MaterialUpdateInput";
import { Material } from "./Material";
import { PoItemFindManyArgs } from "../../poItem/base/PoItemFindManyArgs";
import { PoItem } from "../../poItem/base/PoItem";
import { PoItemWhereUniqueInput } from "../../poItem/base/PoItemWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MaterialControllerBase {
  constructor(
    protected readonly service: MaterialService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Material })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: MaterialCreateInput): Promise<Material> {
    return await this.service.create({
      data: {
        ...data,

        uoMCode: {
          connect: data.uoMCode,
        },
      },
      select: {
        createdAt: true,
        id: true,
        materialDescription: true,
        materialNo: true,

        uoMCode: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Material] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(MaterialFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Material[]> {
    const args = plainToClass(MaterialFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        materialDescription: true,
        materialNo: true,

        uoMCode: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Material })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: MaterialWhereUniqueInput
  ): Promise<Material | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        materialDescription: true,
        materialNo: true,

        uoMCode: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Material })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() data: MaterialUpdateInput
  ): Promise<Material | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          uoMCode: {
            connect: data.uoMCode,
          },
        },
        select: {
          createdAt: true,
          id: true,
          materialDescription: true,
          materialNo: true,

          uoMCode: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Material })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: MaterialWhereUniqueInput
  ): Promise<Material | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          materialDescription: true,
          materialNo: true,

          uoMCode: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PoItem",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/poItems")
  @ApiNestedQuery(PoItemFindManyArgs)
  async findManyPoItems(
    @common.Req() request: Request,
    @common.Param() params: MaterialWhereUniqueInput
  ): Promise<PoItem[]> {
    const query = plainToClass(PoItemFindManyArgs, request.query);
    const results = await this.service.findPoItems(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        currency: true,
        id: true,

        material: {
          select: {
            id: true,
          },
        },

        poHeader: {
          select: {
            id: true,
          },
        },

        quantity: true,

        unitofMeasures: {
          select: {
            id: true,
          },
        },

        unitPrice: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/poItems")
  async connectPoItems(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() body: PoItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      poItems: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/poItems")
  async updatePoItems(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() body: PoItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      poItems: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/poItems")
  async disconnectPoItems(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() body: PoItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      poItems: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
